name: Node Projekt

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: debian-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 19

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
